# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://anubhavashok.github.io/
baseurl: /volvo_website/
title: Volvo-CMU MSCV Capstone 2017
author: Anubhav Ashok & Yifan Xing 
description: Website report for Volvo-MSCV Capstone
avatar1: volvo_construction_logo.png
avatar2: cmu_logo.png
model_compression_image: n2n_pipeline.png
tracking_image: tracking.png
#email: yourname@email.com
#github: myjekyll/sustain # username
#twitter: username
#linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
